custom:
  - 'TON: UQAQ6hegIZbejKThqa3BYyuo7AX8yuRO2f8yQOP7Ke_QVWe9'
  - 'USDT (TRC20): TU8NDNVZJjHtJYLXPz124ZxxszDejjZcp3'
  - 'Solana (SOL): EAcmVHj1HSnSvtVCdFirBnA6wh7BiETmssN1yPjUnTvg'
  - 'BNB Chain / EVM: 0x56731151d6Ff21777f215499A46fC43843590D5b'
